CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS product_db;
CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS payment_db;
CREATE DATABASE IF NOT EXISTS saga_db;

CREATE USER IF NOT EXISTS 'danial'@'%' IDENTIFIED BY 'nopass';
GRANT ALL PRIVILEGES ON *.* TO 'danial'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
