#version: '3.9'

services:
  mariadb:
    image: yobasystems/alpine-mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: danial
      MYSQL_PASSWORD: nopass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql-init/maria-db.cnf:/etc/mysql/conf.d/my.cnf # optional
      - D:/docker-data/mysql_data:/var/lib/mysql
    mem_limit: 60m
    networks:
      - shared-net
      - app_network

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start --overprovisioned --smp 1 --memory 128M --reserve-memory 0M --node-id 0 --check=false --set redpanda.auto_create_topics_enabled=true  --kafka-addr PLAINTEXT://0.0.0.0:9092 --advertise-kafka-addr PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
    mem_limit: 160m
    networks:
      - app_network
      - shared-net
  # -----------------
  # Kafka UI for Monitoring
  # -----------------
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9093:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=redpanda:9092
    networks:
      - app_network
      - shared-net

networks:
  shared-net:
    name: shared-net  # auto-created if missing
  app_network:
    driver: bridge
