server:
  port: 8761

spring:
  application:
    name: discovery-server
  main:
    banner-mode: off
  jmx:
    enabled: false
  devtools:
    add-properties: false

eureka:
  client:
    register-with-eureka: false  # Server does not register itself
    fetch-registry: false        # Server does not fetch other registries
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 60000


management:
  endpoints:
    enabled-by-default: false